[package]
name = "erc4626"
version = "0.1.0"
edition = "2023_11"

[dependencies]
openzeppelin = ">=0.19.0"
starknet = ">=2.6.0"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.32.0" }

[lib]

[[target.starknet-contract]]
sierra = true
casm = true
allowed-libfuncs-list.name = "experimental"

[cairo]
sierra-replace-ids = true

[tool.fmt]
sort-module-level-items = true
